GET http://localhost:3001/api/blogs/
###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
{
    "title": "My Second Awesome Blog",
    "author": "Lorenzo",
    "url": "https://blog.lorenzo.com",
    "likes": 100
}
###
DELETE  http://localhost:3001/api/blogs/62041fbabf647bd9a53563bd HTTP/1.1
content-type: application/json
###
PUT http://localhost:3001/api/blogs/62041a835830be37a16e5db0 HTTP/1.1
content-type: application/json

{
    "title": "My Awesome Blog",
    "author": "Lorenzo",
    "url": "https://blog.lorenzo.com",
    "likes": 12
}
###
POST http://localhost:3001/api/blogs/62041fbabf647bd9a53563bd/comments HTTP/1.1
content-type: application/json

{
    "title": "My Awesome Blog",
    "author": "Lorenzo",
    "url": "https://blog.lorenzo.com",
    "likes": 12,
    "comments": ["Comentario1", "Comentario2"]
}
